### ISSUE TITLE
Hosting pre-trained models

### ISSUE THREAD

**Issue by guysoft** [readbeyond/lachesis#6]
Hey, so as the README suggests you were planning to host pre-trained models. Are you still doing that?
Do you need any hosting?

**Comment by pettarin** [comment]
Hi, unfortunately the project has gone in "hold" state for a while now, since I have switched to a full time day job, and I can no longer work on all the FLOSS projects I started.

In case, I do have a VPS where to host the models, thanks for asking.

**Comment by himat** [comment]
Where do we get the crf models from?

**Comment by readbeyond** [comment]
I just started producing CRF models when I had to halt working on lachesis. So no CRF are available. I am not sure if / when I will have time to resume working on this project.
