### ISSUE TITLE
IOError: Unable to download CC data, please check your Internet connection.

### ISSUE THREAD

**Issue by braincoded** [readbeyond/lachesis#7]
Hi there,
Thank you very much for this great project of yours!

I'm a newbie struggling with the following error when trying to run the first example from the readme ("Download closed captions from YouTube"):

```
[Command: python -u /Users/vm/Downloads/lachesis/lachesis-test.py]
Traceback (most recent call last):
  File "/Users/vm/Downloads/lachesis/lachesis-test.py", line 15, in <module>
    doc = Downloader.download_closed_captions(url, language, options)
  File "/Users/vm/Envs/lachesis/lib/python2.7/site-packages/lachesis/downloaders/downloader.py", line 118, in download_closed_captions
    raise IOError(u"Unable to download CC data, please check your Internet connection.")
IOError: Unable to download CC data, please check your Internet connection.
```
The Internet connection is up an running and the problem both occurs when running lachesis directly on MacOS as well as setting it up with virtualenvwrapper.
Any suggestions on how to solve the problem would be very much appreciated!

**Comment by readbeyond** [comment]
Maybe youtube-dl needs to be updated. From time to time, YouTube changes something in their API that breaks youtube-dl, and a new version of the latter usually follows in a couple of days.

Note, however, that the development of lachesis has been in stall for some time now, I am not really sure when I will have time to resume working on it.
